name: united_formation_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  hydrated_bloc: ^10.0.0
  icons_launcher: ^3.0.0
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl: ^0.19.0
  intl_utils: ^2.8.10
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  rename: ^3.0.2
  retrofit: ^4.4.2
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

# Flutter configuration
flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/svgs/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
# Internationalization configuration
flutter_intl:
  enabled: true
  generate: true

icons_launcher:
  image_path: "assets/images/app_logo.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
