name: united_formation_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+11

environment:
  sdk: ^3.7.0

dependencies:
  app_links: ^7.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.3.1
  dio: ^5.9.1
  equatable: ^2.0.8
  fancy_shimmer_image: ^2.0.3
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  google_sign_in: ^7.2.0
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.2.0
  hydrated_bloc: ^10.1.1
  icons_launcher: ^3.0.3
  image_picker: ^1.2.1
  internet_connection_checker_plus: ^2.9.1
  intl: ^0.20.2
  json_annotation: ^4.10.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  rename: ^3.1.0
  retrofit: ^4.9.2
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  skeletonizer: ^2.1.3
  upgrader: ^12.5.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1

dev_dependencies:
  build_runner: ^2.11.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.2
  icons_launcher: ^3.0.3
  json_serializable: ^6.12.0
  retrofit_generator: ^10.2.3

# Flutter configuration
flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/svgs/
  # example:
  fonts:
    - family: MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
# Internationalization configuration
flutter_intl:
  enabled: true
  generate: true

icons_launcher:
  3.0.3:
    android: true
    ios: true
  platforms:
    android:
      enable: true
    ios:
      enable: true
